In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [3]:
# Load the training dataset
train_data = pd.read_csv('/home/arnab/Desktop/Doceree-HCP_Train.csv',encoding = "latin-1")
train_data.head()

ID DEVICETYPE  PLATFORM_ID    BIDREQUESTIP  \
0  1001    Desktop            2    170.173.0.22   
1  1002    Desktop            2   65.216.253.25   
2  1003    Desktop            2    66.232.79.22   
3  1004    Desktop            3  137.54.125.246   
4  1005     Mobile            7  174.202.231.99   

                        USERPLATFORMUID     USERCITY  USERZIPCODE  \
0  6974dcaa-f932-480e-9fb5-c52e20e1393a     Portland      97206.0   
1  c12f3f8f-8fcf-484a-90e1-1ac04db8cdcf    Arlington      22202.0   
2  a698de4b-e200-46dd-b5fb-40402175ae18  New Meadows      83654.0   
3  45967533-75c8-4fbd-a00c-e6ff20447aaa          NaN  229114624.0   
4  a17e25be-532d-4cf5-b916-9308c8c3961f      Houston      77008.0   

                                           USERAGENT            PLATFORMTYPE  \
0  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
1  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
2  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
3  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
4  Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like...  Online Medical Journal   

  CHANNELTYPE                                                URL  \
0     Website  https://www.cancertherapyadvisor.com/home/canc...   
1     Website  https://www.cancertherapyadvisor.com/home/deci...   
2     Website  https://www.cancertherapyadvisor.com/home/canc...   
3     Website  https://globalrph.com/medcalcs/warfarin-mainte...   
4     Website  https://www.cureus.com/articles/58184-a-review...   

                                            KEYWORDS    TAXONOMY  IS_HCP  
0  General|Endocrine|False|Medicine|Surgery|Urolo...         NaN     0.0  
1  Bone Marrow|Radiography|Chronic|Oncology|Psych...         NaN     0.0  
2  General|Endocrine|False|Medicine|Surgery|Urolo...         NaN     0.0  
3  Dental|Total|Clinical|Pharmacology|Physicians|...  2084P0800X     1.0  
4  Critical Care|Emergency Medicine|General Pract...         NaN     0.0

In [4]:
# Preprocess the training data
train_data = train_data.drop('CHANNELTYPE', axis=1)  # Drop the 'CHANNELTYPE' column
train_data = train_data.drop('ID', axis=1)  # Drop the 'id' column
train_data = train_data.fillna('Unknown')  # Fill missing values with 'Unknown'
taxonomy_data=train_data.drop('IS_HCP',axis=1)
hcp_data=train_data.drop('TAXONOMY',axis=1)

In [5]:
hcp_data.head()

DEVICETYPE  PLATFORM_ID    BIDREQUESTIP  \
0    Desktop            2    170.173.0.22   
1    Desktop            2   65.216.253.25   
2    Desktop            2    66.232.79.22   
3    Desktop            3  137.54.125.246   
4     Mobile            7  174.202.231.99   

                        USERPLATFORMUID     USERCITY  USERZIPCODE  \
0  6974dcaa-f932-480e-9fb5-c52e20e1393a     Portland      97206.0   
1  c12f3f8f-8fcf-484a-90e1-1ac04db8cdcf    Arlington      22202.0   
2  a698de4b-e200-46dd-b5fb-40402175ae18  New Meadows      83654.0   
3  45967533-75c8-4fbd-a00c-e6ff20447aaa      Unknown  229114624.0   
4  a17e25be-532d-4cf5-b916-9308c8c3961f      Houston      77008.0   

                                           USERAGENT            PLATFORMTYPE  \
0  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
1  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
2  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
3  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
4  Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like...  Online Medical Journal   

                                                 URL  \
0  https://www.cancertherapyadvisor.com/home/canc...   
1  https://www.cancertherapyadvisor.com/home/deci...   
2  https://www.cancertherapyadvisor.com/home/canc...   
3  https://globalrph.com/medcalcs/warfarin-mainte...   
4  https://www.cureus.com/articles/58184-a-review...   

                                            KEYWORDS IS_HCP  
0  General|Endocrine|False|Medicine|Surgery|Urolo...    0.0  
1  Bone Marrow|Radiography|Chronic|Oncology|Psych...    0.0  
2  General|Endocrine|False|Medicine|Surgery|Urolo...    0.0  
3  Dental|Total|Clinical|Pharmacology|Physicians|...    1.0  
4  Critical Care|Emergency Medicine|General Pract...    0.0

In [6]:
taxonomy_data['TAXONOMY'].value_counts()

Unknown       81624
2084P0800X     7930
2084N0400X     6621
207Q00000X     3997
207R00000X     3190
              ...  
163WC0400X        1
246QM0706X        1
1835N1003X        1
207RI0008X        1
207XX0801X        1
Name: TAXONOMY, Length: 208, dtype: int64

In [7]:
#Encoding text to numeric data
le = LabelEncoder()
for col in hcp_data.columns:
    hcp_data[col] = le.fit_transform(hcp_data[col].astype(str))  
hcp_data.head()

DEVICETYPE  PLATFORM_ID  BIDREQUESTIP  USERPLATFORMUID  USERCITY  \
0           0            7          6580            22183      3177   
1           0            7         19253            40577       130   
2           0            7         19704            34969      2701   
3           0            8          4193            14676      4018   
4           1           12         10056            33845      1767   

   USERZIPCODE  USERAGENT  PLATFORMTYPE   URL  KEYWORDS  IS_HCP  
0        10913       2857             3   666       459       0  
1         1900       2672             3   708       109       0  
2         9156       2672             3   666       459       0  
3         1959       2945             3   327       274       1  
4         8359       4049             3  1631       258       0

In [8]:
y_taxonomy=np.array(taxonomy_data['TAXONOMY'])
taxonomy_data=taxonomy_data.drop('TAXONOMY',axis=1)  
taxonomy_data.head()

DEVICETYPE  PLATFORM_ID    BIDREQUESTIP  \
0    Desktop            2    170.173.0.22   
1    Desktop            2   65.216.253.25   
2    Desktop            2    66.232.79.22   
3    Desktop            3  137.54.125.246   
4     Mobile            7  174.202.231.99   

                        USERPLATFORMUID     USERCITY  USERZIPCODE  \
0  6974dcaa-f932-480e-9fb5-c52e20e1393a     Portland      97206.0   
1  c12f3f8f-8fcf-484a-90e1-1ac04db8cdcf    Arlington      22202.0   
2  a698de4b-e200-46dd-b5fb-40402175ae18  New Meadows      83654.0   
3  45967533-75c8-4fbd-a00c-e6ff20447aaa      Unknown  229114624.0   
4  a17e25be-532d-4cf5-b916-9308c8c3961f      Houston      77008.0   

                                           USERAGENT            PLATFORMTYPE  \
0  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
1  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
2  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
3  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   
4  Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like...  Online Medical Journal   

                                                 URL  \
0  https://www.cancertherapyadvisor.com/home/canc...   
1  https://www.cancertherapyadvisor.com/home/deci...   
2  https://www.cancertherapyadvisor.com/home/canc...   
3  https://globalrph.com/medcalcs/warfarin-mainte...   
4  https://www.cureus.com/articles/58184-a-review...   

                                            KEYWORDS  
0  General|Endocrine|False|Medicine|Surgery|Urolo...  
1  Bone Marrow|Radiography|Chronic|Oncology|Psych...  
2  General|Endocrine|False|Medicine|Surgery|Urolo...  
3  Dental|Total|Clinical|Pharmacology|Physicians|...  
4  Critical Care|Emergency Medicine|General Pract...

In [9]:
le1 = LabelEncoder()
for col in taxonomy_data.columns:
    taxonomy_data[col] = le1.fit_transform(taxonomy_data[col].astype(str))  
taxonomy_data.head()

DEVICETYPE  PLATFORM_ID  BIDREQUESTIP  USERPLATFORMUID  USERCITY  \
0           0            7          6580            22183      3177   
1           0            7         19253            40577       130   
2           0            7         19704            34969      2701   
3           0            8          4193            14676      4018   
4           1           12         10056            33845      1767   

   USERZIPCODE  USERAGENT  PLATFORMTYPE   URL  KEYWORDS  
0        10913       2857             3   666       459  
1         1900       2672             3   708       109  
2         9156       2672             3   666       459  
3         1959       2945             3   327       274  
4         8359       4049             3  1631       258

In [10]:
le2 = LabelEncoder()
y_taxonomy= le2.fit_transform(y_taxonomy.astype(str))  
y_taxonomy

array([207, 207, 207, ..., 112, 149, 149])

In [11]:
y_hcp=hcp_data['IS_HCP']
y_hcp

0         0
1         0
2         0
3         1
4         0
         ..
113932    1
113933    1
113934    1
113935    1
113936    1
Name: IS_HCP, Length: 113937, dtype: int64

In [12]:
print(y_taxonomy)
type(y_taxonomy)

[207 207 207 ... 112 149 149]


numpy.ndarray

In [13]:
print(y_hcp)
type(y_hcp)

0         0
1         0
2         0
3         1
4         0
         ..
113932    1
113933    1
113934    1
113935    1
113936    1
Name: IS_HCP, Length: 113937, dtype: int64


pandas.core.series.Series

In [14]:
# Split the data into train and validation sets
X_hcp=hcp_data.drop('IS_HCP',axis=1)

X_train_hcp, X_val_hcp, y_train_hcp, y_val_hcp= train_test_split(
    X_hcp, y_hcp, test_size=0.2, random_state=42
)

X_train_taxonomy, X_val_taxonomy, y_train_taxonomy, y_val_taxonomy = train_test_split(
    taxonomy_data, y_taxonomy, test_size=0.2, random_state=42
)

In [15]:
# Build the IS_HCP model (Random Forest Classifier)
model_hcp = RandomForestClassifier(n_estimators=100, random_state=42)
model_hcp.fit(X_train_hcp, y_train_hcp)

RandomForestClassifier(random_state=42)

In [16]:
#Model Scores
print('Train Error:')
print(1-model_hcp.score(X_train_hcp, y_train_hcp))
print('Validation Error:')
print(1-model_hcp.score(X_val_hcp, y_val_hcp))

Train Error:
0.0
Validation Error:
0.006406880814463722


In [17]:
# Build the TAXONOMY model (Random Forest Classifier)
model_taxonomy = RandomForestClassifier(n_estimators=100, random_state=42)
model_taxonomy.fit(X_train_taxonomy, y_train_taxonomy)

RandomForestClassifier(random_state=42)

In [18]:
#Model Scores
print('Train Error:')
print(1-model_taxonomy.score(X_val_taxonomy,y_val_taxonomy))
print('Validation Error:')
print(1-model_taxonomy.score(X_val_taxonomy,y_val_taxonomy))

Train Error:
0.08456205020186058
Validation Error:
0.08456205020186058


In [19]:
# Load the testing dataset
test_data = pd.read_csv('/home/arnab/Desktop/Doceree-HCP_Test.csv',encoding="latin-1")
test_data

ID DEVICETYPE  PLATFORM_ID     BIDREQUESTIP  \
0      115501    Desktop            2   75.189.231.103   
1      115502     Mobile            2    24.101.33.158   
2      115503    Desktop            2  172.118.216.142   
3      115504    Desktop            7   71.105.120.171   
4      115505    Desktop            2     73.82.211.73   
...       ...        ...          ...              ...   
28488  143989    Desktop            2   69.202.233.241   
28489  143990    Desktop            7      75.4.190.65   
28490  143991    Desktop            7    137.52.180.45   
28491  143992    Desktop            8      66.249.66.4   
28492  143993    Desktop            2   107.194.33.149   

                            USERPLATFORMUID         USERCITY  USERZIPCODE  \
0      0d5041ff-f0b6-4d1a-9ad7-0a29f7d485b4     Fayetteville      28305.0   
1      c8396dd0-969f-4d99-a40b-b7bb1f516154    Conneaut Lake      16316.0   
2      3c97a081-6518-43f8-9f26-369759cfb471           Covina      91724.0   
3      3e2578c8-f794-41af-a38c-c5cfb3c0f014         Brooklyn      11226.0   
4      ec2ae7ce-6a8c-4156-98a7-07203e60f483         Marietta      30062.0   
...                                     ...              ...          ...   
28488  78ce4bbe-3885-4c14-b945-a0ea1e4574f4         Brooklyn      11215.0   
28489  a53799e1-b279-40cf-b467-11b4d659e325            Miami      33178.0   
28490  acc732a8-2ee9-4e2c-9933-70e34db48101  Fort Lauderdale      33314.0   
28491  dce21294-b105-4abb-b145-4e62d71def44              NaN          NaN   
28492  f9b193b0-82b0-4ac8-b24a-5635401ca934       Wilmington      28412.0   

                                               USERAGENT  \
0      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...   
1      Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like...   
2      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...   
3      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...   
4      Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   
...                                                  ...   
28488  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...   
28489  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   
28490  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...   
28491  Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...   
28492  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...   

                 PLATFORMTYPE CHANNELTYPE  \
0      Online Medical Journal     Website   
1      Online Medical Journal     Website   
2      Online Medical Journal     Website   
3      Online Medical Journal     Website   
4      Online Medical Journal     Website   
...                       ...         ...   
28488  Online Medical Journal     Website   
28489  Online Medical Journal     Website   
28490  Online Medical Journal     Website   
28491  Online Medical Journal     Website   
28492  Online Medical Journal     Website   

                                                     URL  \
0      https://www.clinicaladvisor.com/home/features/...   
1      https://www.ophthalmologyadvisor.com/topics/ca...   
2      https://www.psychiatryadvisor.com/author/tori-...   
3      https://www.cureus.com/articles/105482-diverti...   
4      https://www.renalandurologynews.com/home/confe...   
...                                                  ...   
28488  https://www.renalandurologynews.com/home/news/...   
28489  https://www.cureus.com/publish/articles/144818...   
28490  https://www.cureus.com/registrations/continue?...   
28491  https://radrounds.com/radiology-case-images-te...   
28492  https://www.clinicalpainadvisor.com/regulatory...   

                                                KEYWORDS  
0      Family Practice|Drainage|Clinical|Dermatology|...  
1      General|Clinical|Operative|Medicine|Cardiology...  
2      Abortion|Anxiety Disorders|Apnea|False|Trauma|...  
3      Health|Male|Neurological Surgery|Otolaryngolog...  
4      chronic kidney disease|pain|nephrology|disease...  
...                                                 

In [20]:
# Preprocess the testing data
test_data = test_data.drop('CHANNELTYPE', axis=1)  # Drop the 'CHANNELTYPE' column
id_col=test_data['ID']#Saving the original id
test_data = test_data.drop('ID', axis=1)  # Drop the 'ID' column
test_data = test_data.fillna('Unknown')  # Fill missing values with 'Unknown'
test_hcp_data=test_data
test_taxo_data=test_data
test_data.head()

DEVICETYPE  PLATFORM_ID     BIDREQUESTIP  \
0    Desktop            2   75.189.231.103   
1     Mobile            2    24.101.33.158   
2    Desktop            2  172.118.216.142   
3    Desktop            7   71.105.120.171   
4    Desktop            2     73.82.211.73   

                        USERPLATFORMUID       USERCITY USERZIPCODE  \
0  0d5041ff-f0b6-4d1a-9ad7-0a29f7d485b4   Fayetteville     28305.0   
1  c8396dd0-969f-4d99-a40b-b7bb1f516154  Conneaut Lake     16316.0   
2  3c97a081-6518-43f8-9f26-369759cfb471         Covina     91724.0   
3  3e2578c8-f794-41af-a38c-c5cfb3c0f014       Brooklyn     11226.0   
4  ec2ae7ce-6a8c-4156-98a7-07203e60f483       Marietta     30062.0   

                                           USERAGENT            PLATFORMTYPE  \
0  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6...  Online Medical Journal   
1  Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like...  Online Medical Journal   
2  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...  Online Medical Journal   
4  Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...  Online Medical Journal   

                                                 URL  \
0  https://www.clinicaladvisor.com/home/features/...   
1  https://www.ophthalmologyadvisor.com/topics/ca...   
2  https://www.psychiatryadvisor.com/author/tori-...   
3  https://www.cureus.com/articles/105482-diverti...   
4  https://www.renalandurologynews.com/home/confe...   

                                            KEYWORDS  
0  Family Practice|Drainage|Clinical|Dermatology|...  
1  General|Clinical|Operative|Medicine|Cardiology...  
2  Abortion|Anxiety Disorders|Apnea|False|Trauma|...  
3  Health|Male|Neurological Surgery|Otolaryngolog...  
4  chronic kidney disease|pain|nephrology|disease...

In [21]:
for col in test_hcp_data.columns:
    test_hcp_data[col] = le.fit_transform(test_hcp_data[col].astype(str))    

for col in test_taxo_data.columns:
    test_taxo_data[col] = le1.fit_transform(test_taxo_data[col].astype(str))        

In [22]:
# Step 9: Make predictions on the testing data
y_pred_hcp = model_hcp.predict(test_hcp_data)
print(y_pred_hcp)
y_pred_taxonomy = model_taxonomy.predict(test_taxo_data)
print(y_pred_taxonomy)
len(y_pred_taxonomy)

[1 0 0 ... 1 1 0]
[207 207 207 ... 207 207 207]


28493

In [23]:
predictions_taxonomy = le2.inverse_transform(y_pred_taxonomy)
print(len(predictions_taxonomy))
np.unique(predictions_taxonomy,return_counts=True)

28493


(array(['207Q00000X', '207R00000X', '207RC0200X', '2080P0202X',
        '2084N0400X', '2084P0800X', '2084P0802X', 'Unknown'], dtype='<U10'),
 array([    8,     3,     1,     1,   743,   141,     1, 27595]))

In [24]:
#Examining cases where taxonomy and hcp clashes
for i in range(len(predictions_taxonomy)):
    if(y_pred_hcp[i]==0):
        if(predictions_taxonomy[i]=='Unknown'):
            continue
        else:
            predictions_taxonomy[i]='Unknown'
for i in range(len(predictions_taxonomy)):
    if(predictions_taxonomy[i]=='Unknown'):
        predictions_taxonomy[i]=''           

In [25]:
#Generate submission file
sample_submission = pd.DataFrame({'ID': id_col, 'IS_HCP': y_pred_hcp})
sample_submission.head()

ID  IS_HCP
0  115501       1
1  115502       0
2  115503       0
3  115504       1
4  115505       0

In [26]:
complete_submission = pd.DataFrame({'ID': id_col, 'IS_HCP': y_pred_hcp, 'TAXONOMY': predictions_taxonomy})
complete_submission

ID  IS_HCP TAXONOMY
0      115501       1         
1      115502       0         
2      115503       0         
3      115504       1         
4      115505       0         
...       ...     ...      ...
28488  143989       1         
28489  143990       1         
28490  143991       1         
28491  143992       1         
28492  143993       0         

[28493 rows x 3 columns]

In [27]:
sample_submission.to_csv('sample_submission.csv', index=False)
complete_submission.to_csv('complete_submission.csv', index=False)